# Model Hyperparams

seed : 42
epochs : 10
dataset : 'MaskSplitByProfileDataset' # MaskDataset, MaskSplitByProfileDataset
augmentation : 'CustomAugmentation'
resize : [256,192]
batch_size : 16
model : "EfficientNet_b0" 

# Training

optimizer : 'Adam'
lr : 0.00002
val_ratio : 0.2
criterion : 'f1'
lr_decay_step : 20
log_interval : 20
name : 'exp69'

# Validation

validation_interval : 1
valid_batch_size : 64

# Test
test_data_dir : '/opt/ml/input/data/eval'
test_batch_size : 64
test_model : 'exp69'

# WANDB
 
wandb : True
# Container environment

data_dir : '/opt/ml/input/data/train/images'
model_dir : './model/EfficientNet_b0'
output_dir : './inferenceoutput'
